# Generated by Django 4.2.9 on 2024-02-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0006_fotografia_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotografia",
            name="publicada",
            field=models.BooleanField(default=True),
        ),
    ]
